#!/usr/bin/env bash

docker run --name dev \
  --hostname dev \
  -v "$PWD":/home/benjaminoakes/workspace \
  -d -it dev
# After first start, run `docker container start dev` then attach
docker attach dev
