#!/usr/bin/env bash

docker_gid=$(getent group docker | cut -d: -f3)

docker run --name dev \
  --hostname dev \
  -v "$PWD":/home/benjaminoakes/workspace \
  -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK \
  -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
  -e DOCKER_GID=$docker_gid \
  --privileged \
  -v `readlink -f /var/run/docker.sock`:/var/run/docker.sock \
  -d -it dev
